### PR TITLE
html reporter

### PR DESCRIPTION
**Pull request by BeataKr**
`html` reporter will disable printed to logs violations

there is no point in having logged violations if all are under HTML file, but still, user can use e.g. `default` reporter (which will print everything as usually) and generate an external HTML file (still can disable such one by `doNotCreateReportFile: true` option)

### CODE REVIEW

**Comment by BeataKr** [comment]
@abhinaba-ghosh can you please publish as 1.2.2?

**Comment by BeataKr** [comment]
@abhinaba-ghosh may I ask for release?

**Comment by abhinaba-ghosh** [comment]
@BeataKr this PR does not contain any file changes. Intended?

**Comment by BeataKr** [comment]
You are right, but no idea why it happened if I created the same PR like this one https://github.com/abhinaba-ghosh/axe-playwright/pull/210/files

**Comment by BeataKr** [comment]
@abhinaba-ghosh are able to merge https://github.com/abhinaba-ghosh/axe-playwright/pull/210 and release changes, please?

**Pull request merged**
