### PR TITLE
Bug/detailed report

### PR DESCRIPTION
**Pull request by abannach**
Not all failures were put in the `any` prop and there is the possibility of multiple in each. This gets any messages on the violation and puts them into an array that's stringified out.

### CODE REVIEW

**Comment by abhinaba-ghosh** [comment]
Hey @abannach , after merging the PR, I am getting distorted console messages. Let's not show everything in the tabular format or trim accordingly. A better approach would be minimum information the console and detailed report as a file (ndjson/json/whatever). I am reverting back your PR. I would love to hear from you on how to tackle this situation. 

Screenshot 2020-08-06 at 3 28 49 PM

**Comment by abannach** [comment]
Ah, yeah I guess my terminal is not setup to wrap text. You could always disable the detailed report at runtime or we could default that to false. A file output would probably be best or outputting the detailed report in a `console.log` fashion vs `console.table`. Maybe instead of writing out the error text in the report we could reference the index from the summary table. It would then look a lot cleaner.

| index | target | html | violations |
| ----- | ------ | ----- | --------- |
| 0 | "blah" | "blah" | [0,1,3] |

Thoughts on that approach? or would writing a file be better? Could also come up with a log line that portrays the information with referencing the index of the violations in the summary.

**Comment by abannach** [comment]
@abhinaba-ghosh Here's what I came up with,
image

and with the option of including the html if needed which was a large field

image

**Comment by abhinaba-ghosh** [comment]
Looks really good. I would love to review the PR with an updated readme. Many thanks.

**Pull request merged**
