### PR TITLE
feat: Added new terminal reporter

### LINKED ISSUE #89: Update playwright and axe-core dependencies
We're currently seeing a compatibility issue when using `axe-playwright` in our project.

The type of the property `runOnly` from `axe-core`'s `RunOptions` has changed on a newer version, causing the following error:

```no-highlight
Types of property 'runOnly' are incompatible.
    Type 'string | RunOnly | string[] | undefined' is not assignable to type 'string[] | RunOnly | undefined'.
      Type 'string' is not assignable to type 'string[] | RunOnly | undefined'.
```

Could you please update both `axe-core` and `playwright` dependencies to their latest versions.

Thanks in advance.

### LINKED ISSUE #95: Add log level functionality
Hey, we've been using this lib in our project and that is great! 
However when there are no violations, I'd rather not have any logs. When looking at the results of the tests, there is quite some noise added there. Would it be possible to either remove the log (no error logs should mean success), or add a log level so that these logs only appear when set to "verbose" or something like that?

image

Thank you!

### LINKED ISSUE #96: Improved report messages
As a followup of #95 

One thing I noticed in this library is that there is both a report functionality tied to `assert` and there are a couple console.logs/table happening.

Because the logs are not strictly connected to assert, they will happen at a different time than the assert error message and that might be confusing to users. 

Also, Axe provides a lot of very insightful information that could be covered in the messages coming from this library.

Therefore I'd like to ask what are your thoughts in improving the reports here from:
image

To removing all the logs and passing the error message to assert, looking like (very much inspired by the reports from [jest-axe](https://github.com/nickcolley/jest-axe)):
image

I'd be happy to put up a PR!

### LINKED ISSUE #111: Documented syntax doesn't work in TypeScript
The documentation suggest the following syntax is valid:
```ts
await checkA11y(page, null, {
  detailedReport: true,
})
```

When using this, I get a TypeScript error:
```
Argument of type 'null' is not assignable to parameter of type 'ElementContext | undefined'.ts(2345)
```

If I try to use `undefined` instead, it then complains that I don't provide `axeOptions`:
```
Argument of type '{ detailedReport: true; }' is not assignable to parameter of type 'Options'.
  Property 'axeOptions' is missing in type '{ detailedReport: true; }' but required in type 'axeOptionsConfig'.ts(2345)
index.d.ts(5, 3): 'axeOptions' is declared here.
```

Seems you need to make the `axeOptions` optional:
```ts
export interface axeOptionsConfig {
  axeOptions?: RunOptions
}
```
You'd also want to make `context` nullable:
```ts
export function checkA11y(
  page: Page,
  context?: ElementContext | null,
  options?: Options,
  skipFailures?: boolean,
): Promise<void>
```

### LINKED ISSUE #112: Need to bump version of axe-core to get bug fixes
Our solution is getting false-positives for color-contrast, which seems to be fixed in a newer version of `axe-core`. Would it be possible to bump the version consumed by this plugin?

https://github.com/dequelabs/axe-core/issues/2851

### LINKED ISSUE #124: [ISSUE] - Error in tsconfig.json file
When I have axe-playwright set up, everything seems to work well. But I noticed that there is the following error in the tsconfig.json file: Cannot find type definition file for 'jest'. The file is in the program because: Entry point of type library 'jest' specified in compilerOptions

I am still new to this, so does anyone know how to resolve this error?

### PR DESCRIPTION
**Pull request by bryanjtc**
- Added verbose key
- Added new terminal reporter based on jest-axe
- Upgraded some dependencies
- Updated README with updates
- Added tests for new terminal and verbose key
- Fixes multiple issues
- Changed tsconfig.json to generate type declaration files on build to avoid incorrect type declarations on package
- Reduced package size by only publishing dist folder and README
Fixes #95
Fixes #96
Fixes #112 
Fixes #89 
Fixes #111
Fixes #124

### CODE REVIEW

**Comment by bryanjtc** [comment]
@abannach Can you check this?
I think there aren't breaking changes.

**Comment by bryanjtc** [comment]
@abhinaba-ghosh ?

**Comment by bryanjtc** [comment]
@abhinaba-ghosh Did you check this?

**Review by abhinaba-ghosh — APPROVED** [review]

**Comment by abhinaba-ghosh** [comment]
Thanks for the PR. 

I will relaese a new version today.

**Comment by abhinaba-ghosh** [comment]
This is available in `v1.1.12`

Cheers!

**Pull request merged**
